{% set name = "antio" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ff0d55997f20f1cd01eab731eb9b19665742e183a84ea65b605d7a75d8d06b6

build:
  number: 0
  python_version_independent: true  # [is_abi3]
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [is_abi3 and py != 311]
  entry_points:
    - antio = antio._commands.main:run

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - python-abi3                    # [is_abi3]
    - setuptools >=64.0.0
    - setuptools_scm >=8.0.0
  run:
    - click
    - numpy >=1.23
    - packaging
    - psutil
    - python

test:
  imports:
    - antio
  commands:
    - pip check
    - python -c "from antio.libeep import pyeep; version = pyeep.get_version(); assert version == '3.3.179', version"
    - python -c "import importlib.metadata; ver = importlib.metadata.version('antio'); assert ver == '{{ version }}', ver"
    - python -c "import antio; ver = antio.__version__; assert ver == '{{ version }}', ver"
    - abi3audit $SP_DIR/antio/libeep/pyeep.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}   # [unix and is_abi3]
    - abi3audit %SP_DIR%/antio/libeep/pyeep.pyd -s -v --assume-minimum-abi3 {{ python_min }}      # [win and is_abi3]
  requires:
    - pip
    - abi3audit                      # [is_abi3]

about:
  home: https://github.com/mscheltienne/antio
  summary: Python package to handle I/O with the CNT format from ANT Neuro.
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - src/libeep/LICENSE
    - src/libeep/LICENSE.addendum
  dev_url: https://github.com/mscheltienne/antio

extra:
  recipe-maintainers:
    - mscheltienne
    - larsoner
