{% set name = "antio" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e92cd32d8c881ffdd4ce613f3f9af4d6dae76cb8538c85e4add920411d7e8e01

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]
  entry_points:
    - antio = antio.commands.main:run

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=64.0.0
  run:
    - click
    - numpy >=1.23
    - packaging
    - psutil
    - python

test:
  imports:
    - antio
  commands:
    - pip check
    - python -c "from antio.libeep import pyeep; version = pyeep.get_version(); assert version == '3.3.179', version"
    - antio
  requires:
    - pip

about:
  home: https://github.com/mscheltienne/antio
  summary: Python package to handle I/O with the CNT format from ANT Neuro.
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - src/libeep/LICENSE
    - src/libeep/LICENSE.addendum
  dev_url: https://github.com/mscheltienne/antio

extra:
  recipe-maintainers:
    - mscheltienne
    - larsoner
